### ISSUE TITLE
add weak references in the syntax to allow mutual references

### ISSUE THREAD

**Issue by SenseLogic** [crack-lang/crack#8]
I suggest that you add a way to declare both weak references and pointers, in complement to the default strong references.

When an object looses its last strong reference (= null strong reference count), it is immediately destroyed (= its destructor is called).

But the object memory block is released only when it looses its last weak reference (= null weak reference count). 

Meanwhile the weak references will behave as if they were null when using them, as the object they are pointing to has been destroyed.

The object memory block is deallocated only when the last weak reference is also lost.

There is a sample implementation here :

https://github.com/senselogic/BASE/tree/master/CODE/COUNTED

Weak references are very useful for instance to easily declare double-linked tree structures, where the parent node holds an array of strong references to the child nodes (for downward traversal), and each child node also keeps a weak reference to its parent (for upward traversal).

About the syntax, I suggest adding a postfix character (!) to the type :

class NODE
{
    NODE! ParentNode;    // weak reference to the parent node
    array[NODE] ChildNodeArray;    // array of strong references to the child nodes
    ...
}

And inside the tree traversal code, I suggest we also have to possibility to also use raw pointer types (@) to just hold the address of a node in highly optimized code, at the expense of some safety.

NODE doSomething()
{
    NODE@ node, childnode;
    for(...) {
        if (...) node = childnode;
        else node = childnode.ParentNode;
    }
    return node;
}

**Comment by senselogic** [comment]
Btw for the weak reference type suffix, I'd rather suggest '^', which seems a more intuitive character for such "back" references.

This way :
- T is a strong reference (by default);
- T^ is a weak reference.

**Comment by senselogic** [comment]
PS: and if you wonder why I'm suggesting to add weak references and typed pointers, it's because 
Crack's automatic reference counting system makes it de facto one of the best C++ alternatives, as it's much easier to use than both Rust and C++, and contrarily to D and all the other C++ derivatives which have chosen to use a garbage collector, after a few minor adjustments Crack could soon be used to program practically anything which is currently implemented in C++, including soft-realtime applications like games, which could broaden a lot its audience.

**Comment by mindhog** [comment]
[apologies, I responded via e-mail but apparently that didn't take]

Thanks for the suggestion!  Replied inline below.

SenseLogic wrote:
> I suggest that you add a way to declare both weak references and pointers, in complement to the default strong references.

You can do most of that already through the use of non-Object derived base
classes (for example, VTableBase).  This creates a class without Object's
reference counting machinery:

import crack.cont.array Array;
import crack.io cerr;
import crack.lang FreeBase;

class _NodeBase : VTableBase {
    _NodeBase parent;

    oper init() {}
    oper init(_NodeBase parent) : parent = parent {}
}

class Node : Object, _NodeBase {
    String name;
    Array[Node] children;

    oper init(String name, _NodeBase parent) : _NodeBase(parent), name = name {}
    oper init(String name) : _NodeBase(null), name = name {}

    ## Make a new child and return it.
    Node makeChild(String name) {
        result := Node(name, this);
        if (!children)
            children = Array[Node]![result];
        else
            children.append(result);
        return result;
    }

    oper del() {
        # Clean up parent links in all children.
        cerr `deleting $name\n`;
        if (children) {
            for (child :in children)
                child.parent = null;
        }
    }
}

top := Node('top');
foo := top.makeChild('foo');
foo.makeChild('bar');
foo.makeChild('baz');
top.makeChild('bot');

>
> When an object looses its last strong reference (= null strong reference count), it is immediately destroyed (= its destructor is called).
>
> But the object memory block is released only when it looses its last weak reference (= null weak reference count).
>
> Meanwhile the weak references will behave as if they were null when using them, as the object they are pointing to has been destroyed.

I can't think of any way to make that work without additional runtime
overhead.  Can you?

>
> The object memory block is deallocated only when the last weak reference is also lost.
>
> There is a sample implementation here :
>
> https://github.com/senselogic/BASE/tree/master/CODE/COUNTED
>
> Weak references are very useful for instance to easily declare double-linked tree structures, where the parent node holds an array of str\
ong references to the child nodes (for downward traversal), and each child node also keeps a weak reference to its parent (for upward trave\
rsal).
>
> About the syntax, I suggest adding a postfix character (!) to the type :
>
> class NODE
> {
>     NODE! ParentNode;    // weak reference to the parent node
>     array[NODE] ChildNodeArray;    // array of strong references to the child nodes
>     ...
> }
>
> And inside the tree traversal code, I suggest we also have to possibility to also use raw pointer types (@) to just hold the address of a\
 node in highly optimized code, at the expense of some safety.
>
> NODE doSomething()
> {
>     NODE@ node, childnode;
>     for(...) {
>         if (...) node = childnode;
>         else node = childnode.ParentNode;
>     }
>     return node;
> }

I've long considered adding a "rawptr" generic to the language that would
circumvent the machinery that generates calls to the incref/decref functions.
However, I've come to feel that the approach I describe above is sufficient: I
haven't found a case where I want to do reference cycles that I haven't also
wanted to encode the exception into the class logic, and I haven't thought of
anything that rawptr would add to this (except, perhaps, the temptation for
abuse :-).

The possibility of using a rawptr as an optimization, as you have described,
is attractive.  Though I think that with a bit of restructuring, you can use
a non-Object class to get most of the same benefits.

**Comment by senselogic** [comment]
For the NodeBase solution, indeed it gets the job done, but this implies splitting the class logic into two classes instead of one. Moreover this can't be used on any already existing class, whether it belongs or not to the standard library.

For the weak pointer, indeed there would a memory and runtime overhead, but that would not be a performance killer.

And this way, you can use it on anything, without having to create an uncounted base class just for that.

For the Object class, this would essentially involve :
- having to check the weak-count nullity when decrementing the strong reference count, to see if the object can be destroyed or not.
- a few more bytes per object (for instance 30 bits for the weak reference count, and 2 bits for the destruction state);

Most of the runtime overhead would actually be inside the weak reference class, to check for the object destruction.
And in my experience, an overwhelming majority of an application references are strong references, so there's really nothing to worry about.

And about the typed pointer which can also be used on any type, I'm not suggesting it just as an optimisation. 

Even if the weak reference and the typed pointer look like two conveniency features, IMO they would be enough to make Crack become a perfect C/C++/Rust replacement for many of their typical use cases, including developing AND scripting soft realtime-applications like games.

It's important that realize that at the moment, Crack and Kotlin Native are the only true C++-derivative with automatic reference counting that can be used both for server-side and client-side development, and we are many to dislike Kotlin idiosyncratic design decisions...

So IMO there is not much you need to do add to the language to make it more appealing to the masses.

Just add the weak references and typed pointers, write a nice article explaining how to make a Linux game with Crack and amultimedia library (like Raylib, SFML or SDL), and you may be surprised that several game developers will immediately be interested in helping you port Crack to several other platforms...

Because as I said Crack, as a C++-like language with automatic reference counting, has almost no other alternative in that domain...

**Comment by mindhog** [comment]
Yeah, I'll concede that the non-Object derived solution has some issues.  I can also think of a good way to implement raw pointer as a generic appendage which involves adding a much more general language feature.

I'd also consider doing a "game implementation" article.  Can you recommend a game development blog that would be open to publishing it? 

As far as full weak references go, I can't think of a good case for them if you also have raw pointers.  Can you provide an example of a case where a weak reference would be preferable? (There are also some practical issues with implementing weak references in Crack, which I won't get into here)

**Comment by senselogic** [comment]
Weak references are not required actually, as indeed a simple typed pointer can also get the job done. For instance a simple generic type like Ptr[T].

About the article, IMO all that's needed is to explain :
1/ how to add a Raylib-binding to Crack (for instance) 
2/ how to implement a simplistic tetris clone in Crack (like a port of "https://github.com/raysan5/raylib/blob/master/games/tetris.c")
3/ how to implement a game server in Crack, to store a highscore list
4/ how to provide the top-five list to thegame client so that it can show it if we click on the "Highscores" button of the main game menu.

Personally I'd advice you to try to publish it on GameDev.net, or on Gamasutra.com ("Crack, a high performance game scripting language"), and also mention on Reddit.com (https://www.reddit.com/r/gamedev/) or on Medium.com.

**Comment by mindhog** [comment]
crack.rawptr.RawPtr is implemented in a98dc11ecf5f579e0d012275b9cc0f2acb9ffff7

It will be released as part of Crack 1.4 which I am in the process or releasing.

**Comment by senselogic** [comment]
👍
